#!/bin/bash

ROOT=$(cd $(dirname $0)/..; pwd)
EXE=$(basename $0)
PATH='${ROOT}:${ROOT}/bin:${PATH}' FONTCONFIG_PATH='${ROOT}/etc/fonts' GIT_EXEC_PATH='${ROOT}/libexec/git-core' GIT_TEMPLATE_DIR='${ROOT}/share/git-core' TK_LIBRARY='/System/Library/Frameworks/Tk.framework/Versions/8.5/Resources/Scripts' ${ROOT}/bin_wrapped/${EXE}
