#!/bin/bash

ROOT=$(dirname $(dirname $0))
EXE=$(basename $0)
PATH='${ROOT}:${ROOT}/julia/bin:${PATH}' FONTCONFIG_PATH='${ROOT}/julia/etc/fonts' GIT_EXEC_PATH='${ROOT}/julia/libexec/git-core' GIT_TEMPLATE_DIR='${ROOT}/julia/share/git-core' TK_LIBRARY='/System/Library/Frameworks/Tk.framework/Versions/8.5/Resources/Scripts' ${ROOT}/julia/bin_wrapped/${EXE}
